<?php

/**
 * Implementation of hook_menu().
 */
function dr_solr_menu() {
  $items['dr/solr/taxonomy'] = array(
    'title'            => 'DR: Word match report',
    'page callback'    => 'dr_solr_taxonomy_word_match_report',
    'access arguments' => array('administer search'),
  );
  return $items;
}

function dr_solr_taxonomy_word_match_report_form() {
  drupal_add_css(drupal_get_path('module', 'dr_solr') .'/dr_solr.css');
  $collection_default = is_numeric(arg(3)) ? arg(3) : 'All';
  $type_default = is_string(arg(4)) ? arg(4) : 'dr_post';
  $vocab_default = is_numeric(arg(5)) ? arg(5) : NULL;

  // Collections
  $sql = "SELECT nid, title FROM {node} WHERE type = 'dr_collection' AND status = 1 ORDER BY title ASC";
  $result = db_query($sql);
  $collection_options = array();
  while ($row = db_fetch_object($result)) {
    $collection_options[$row->nid] = $row->title;
  }

  // Node types
  $types = node_get_types('names');
  // Vocabularies
  $vocabularies = taxonomy_get_vocabularies();
  $options = array();
  foreach ($vocabularies as $vocab) {
    $options[$vocab->vid] = $vocab->name;
  }

  $form = array();
  $form['filters'] = array(
    '#type' => 'fieldset',
    '#title' => t('Filters'),
  );
  $form['filters']['collection'] = array(
    '#type' => 'select',
    '#title' => t('Collection'),
    '#options' => array('All' => '<Any>') + $collection_options,
    '#default_value' => $collection_default,
  );
  $form['filters']['type'] = array(
    '#type' => 'select',
    '#title' => t('Content type'),
    '#options' => array('All' => '<Any>') + $types,
    //'#description' => t('Select a content type to filter by nodes only of that type.'),
    '#default_value' => $type_default,
  );
  $form['filters']['vid'] = array(
    '#type' => 'select',
    '#title' => t('Vocabulary'),
    '#options' => $options,
    //'#description' => t('Select a vocabulary from which terms should be used to search for frequency of occurence in posts.'),
    '#default_value' => $vocab_default,
  );
  $form['filters']['buttons']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
  );
  return $form;
}

function dr_solr_taxonomy_word_match_report_form_submit($form, &$form_state) {
  if ($form_state['values']['vid']) {
    $form_state['redirect'] = 'dr/solr/taxonomy/'. $form_state['values']['collection'] .'/'. $form_state['values']['type'] .'/'. $form_state['values']['vid'];
  }
}

function dr_solr_taxonomy_word_match_report() {
  $out = '';
  $out .= drupal_get_form('dr_solr_taxonomy_word_match_report_form');

  $collection = arg(3);
  $type = arg(4);
  $vid = arg(5);

  if ($vid) {
    $header = array(
      t('Term'),
      t('Number of posts'),
    );
    $rows = array();

    $tree = taxonomy_get_tree($vid);
    foreach ($tree as $term) {
      if ($term->name) {
        $query = apachesolr_drupal_query($term->name);
        if ($type !== 'All') {
          $query->add_filter('type', $type);
        }
        $params = array(
          'fl' => 'id,nid',
          'rows' => variable_get('apachesolr_rows', 1),
          'facet' => 'true',
          'facet.mincount' => 1,
        );

        $link_filters = array();
        $link_filters[] = 'is_cck_field_dr_collection:'. $collection;
        $link_filters[] = 'vid:'. $term->vid;
        if ($type !== 'All') {
          $link_filters[] = 'type:'. $type;
        }
        $options = array('query' => array());
        $options['query']['filters'] = implode(' ', $link_filters);
        $options['query']['retain-filters'] = 1;
        $url = 'search/apachesolr_search/'. $term->name;

        list($final_query, $response) = apachesolr_do_query('dr_solr', $query, $params);
        $rows[] = array(
          str_repeat('-', $term->depth) . l($term->name, $url, $options), 
          $response->response->numFound,
        );
      }
    }
    if (count($rows)) {
      $out .= theme('table', $header, $rows, array('id' => 'dr-solr-taxonomy'));
    }
  }
  return $out;
}
