<?php

/**
 * Implementation of hook_menu().
 */
function dr_solr_menu() {
  $items['dr/solr/taxonomy'] = array(
    'title'            => 'DR: Word match report',
    'page callback'    => 'dr_solr_taxonomy_word_match_report',
    'access arguments' => array('search content'),
  );
  return $items;
}

function dr_solr_taxonomy_word_match_report_form() {
  drupal_add_css(drupal_get_path('module', 'dr_solr') .'/dr_solr.css');
  $collection_default = $_GET['collection'] ? $_GET['collection'] : 'All';
  $thread_default = $_GET['thread'] ? $_GET['thread'] : 'All';
  $type_default = $_GET['type'] ? $_GET['type'] : 'dr_post';
  $vocab_default = $_GET['vid'] ? $_GET['vid'] : NULL;
  $exact_default = $_GET['exact'] ? $_GET['exact'] : FALSE;

  // Threads
  $threads_view = views_get_view('threads_by_collection');
  $threads_view->execute();
  $thread_options = array();
  foreach ($threads_view->result as $row) {
    $title = ($row->node_node_data_field_dr_collection_title .': '. $row->node_title);
    $thread_options[$row->nid] = $title;
  }

  // Collections
  $sql = "SELECT nid, title FROM {node} WHERE type = 'dr_collection' AND status = 1 ORDER BY title ASC";
  $result = db_query($sql);
  $collection_options = array();
  while ($row = db_fetch_object($result)) {
    $collection_options[$row->nid] = $row->title;
  }

  // Node types
  $types = node_get_types('names');
  // Vocabularies
  $vocabularies = taxonomy_get_vocabularies();
  $options = array();
  foreach ($vocabularies as $vocab) {
    $options[$vocab->vid] = $vocab->name;
  }

  $form = array();
  $form['filters'] = array(
    '#type' => 'fieldset',
    '#title' => t('Filters'),
  );
  $form['filters']['collection'] = array(
    '#type' => 'select',
    '#title' => t('Collection'),
    '#options' => array('All' => '<Any>') + $collection_options,
    '#default_value' => $collection_default,
  );
  $form['filters']['thread'] = array(
    '#type' => 'select',
    '#title' => t('Thread'),
    '#options' => array('All' => '<Any>') + $thread_options,
    '#default_value' => $thread_default,
  );
  $form['filters']['type'] = array(
    '#type' => 'select',
    '#title' => t('Content type'),
    '#options' => array('All' => '<Any>') + $types,
    //'#description' => t('Select a content type to filter by nodes only of that type.'),
    '#default_value' => $type_default,
  );
  $form['filters']['vid'] = array(
    '#type' => 'select',
    '#title' => t('Vocabulary'),
    '#options' => $options,
    //'#description' => t('Select a vocabulary from which terms should be used to search for frequency of occurence in posts.'),
    '#default_value' => $vocab_default,
  );
  $form['filters']['exact'] = array(
    '#type' => 'checkbox',
    '#title' => t('Exact match'),
    '#default_value' => $exact_default,
  );
  $form['filters']['buttons']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
  );
  return $form;
}

function dr_solr_taxonomy_word_match_report_form_submit($form, &$form_state) {
  if ($form_state['values']['vid']) {
    $query = array(
      'collection' => $form_state['values']['collection'],
      'thread' => $form_state['values']['thread'],
      'type' => $form_state['values']['type'],
      'vid' => $form_state['values']['vid'],
      'exact' => $form_state['values']['exact'],
    );
    $form_state['redirect'] = array('dr/solr/taxonomy/', $query);
  }
}

function dr_solr_taxonomy_word_match_report() {
  $out = '';
  $out .= drupal_get_form('dr_solr_taxonomy_word_match_report_form');

  $collection = $_GET['collection'];
  $thread = $_GET['thread'];
  $type = $_GET['type'];
  $vid = $_GET['vid'];
  $exact = $_GET['exact'];

  if ($vid) {
    $header = array(
      t('Term'),
      t('Number of posts'),
    );
    $rows = array();

    $tree = taxonomy_get_tree($vid);
    foreach ($tree as $term) {
      if ($term->name) {
        $query_string = $term->name;
        if ($exact) {
          $query_string = '"'. $query_string .'"';
        }
        $query = apachesolr_drupal_query($query_string);
        
        // Build the solr query
        if ($type !== 'All') {
          $query->add_filter('type', $type);
        }
        if ($collection !== 'All') {
          $query->add_filter('is_cck_field_dr_collection', $collection);
        }
        if ($thread !== 'All') {
          $query->add_filter('is_cck_field_dr_parent', $thread);
        }
        $params = array(
          'fl' => 'id,nid',
          'rows' => variable_get('apachesolr_rows', 1),
          'facet' => 'true',
          'facet.mincount' => 1,
        );

        // Build the links
        $link_filters = array();
        if ($collection !== 'All') {
          $link_filters[] = 'is_cck_field_dr_collection:'. $collection;
        }
        if ($thread !== 'All') {
          $link_filters[] = 'is_cck_field_dr_parent:'. $thread;
        }
        if ($type !== 'All') {
          $link_filters[] = 'type:'. $type;
        }
        $options = array('query' => array());
        $options['query']['filters'] = implode(' ', $link_filters);
        $options['query']['retain-filters'] = 1;
        $url = 'search/apachesolr_search/'. $query_string;

        list($final_query, $response) = apachesolr_do_query('dr_solr', $query, $params);
        $rows[] = array(
          str_repeat('-', $term->depth) . l($term->name, $url, $options), 
          $response->response->numFound,
        );
      }
    }
    if (count($rows)) {
      $out .= theme('table', $header, $rows, array('id' => 'dr-solr-taxonomy'));
    }
  }
  return $out;
}
